name: talk_to_task
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  file_picker: ^6.1.1   # For picking audio file
  cupertino_icons: ^1.0.8
  record: ^6.0.0
  path_provider: ^2.1.2  # Optional: for saving to temp directory
  path: ^1.9.0           # To handle file paths

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
